from doubleLinkList import doubleLinkList
print("creating list")
list1=doubleLinkList()
list1.createList(2,0)
list1.createList(4,1)
list1.createList(6,2)
list1.createList(8,3)
list1.createList(10,4)
list1.createList(12,5)
list1.createList(14,6)
list1.createList(16,7)
list1.createList(18,8)
list1.createList(20,9)

print("traversing list")
list1.traverse()
print("no of nodes in list are",list1.nodeCount)

print("reverse traversing the list")
list1.reverseTraverse()

print("searching some values in the list")
list1.search(5)
list1.search(8)
list1.search(19)
list1.search(20)

print("traversing the list again")
list1.traverse()
print("no of nodes :",list1.nodeCount)

print("deleting items")
list1.deleteNode(0)
list1.traverse()
print("no of nodes :",list1.nodeCount)
list1.deleteNode(0)
list1.traverse()
print("no of nodes :",list1.nodeCount)
list1.deleteNode(4)
list1.traverse()
print("no of nodes :",list1.nodeCount)
list1.deleteNode(list1.nodeCount)
list1.traverse()
print("no of nodes :",list1.nodeCount)
list1.deleteList()
list1.traverse()
print("no of nodes :",list1.nodeCount)

