from bst import binarySeacrhTree

bst1=binarySeacrhTree()
print("inserting values in bst")
bst1.insert(20)
bst1.insert(10)
bst1.insert(15)
bst1.insert(8)
bst1.insert(5)
bst1.insert(40)
bst1.insert(35)
bst1.insert(50)
bst1.insert(70)

print("traversing the bst")
bst1.traverseIn(bst1.root)
print("\nnode count is:",bst1.nodeCount)
print("deleting the value from tree")
bst1.delete(40)
bst1.traverseIn(bst1.root)
bst1.delete(10)
bst1.traverseIn(bst1.root)
bst1.delete(5)
bst1.traverseIn(bst1.root)
bst1.delete(70)
bst1.traverseIn(bst1.root)
bst1.delete(20)
bst1.traverseIn(bst1.root)
print()
#bst1.delete(4)
#bst1.traverseIn(bst1.root)
#print("\nsearch",bst1.search(bst1.root, 10))

